version: "3.8"

services:
  postgresql:
    image: postgres:14-bullseye
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "db", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgresql
